#!/usr/bin/env python3
"""Build the Kinsta front controller (root index.php) and real-301 stubs from the repo's _redirects file.

Kinsta does not read Netlify's _redirects, and WordPress now only handles /blog/. Any URL that is not a
real file or folder lands on the root index.php, so the redirect map lives there.

Usage (from anywhere):  python3 tools/kinsta/build_front_controller.py
Reads   <repo>/_redirects          (lines: <old-path>  <new-path>  <301|302>, or <old-path>  -  410 for a page that is gone)
Writes  tools/kinsta/index.php     (deploy to the server root: public/index.php)
        <old-path>/index.php       for each old path that still exists as a page folder (a stub page
                                   cannot be redirected by index.php alone, because nginx serves the folder
                                   directly; an index.php beside the stub's index.html takes precedence)
Exit code 1 if the rules have a problem (duplicates, chains, loops, destination page missing).
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'tools', 'kinsta', 'index.php')

HEADER_STUB = """<?php
// GENERATED by tools/kinsta/build_front_controller.py from _redirects. Do not edit by hand.
// A real {status} for this old URL. The index.html beside it stays as a fallback for hosts that cannot redirect.
header( 'Cache-Control: public, max-age=3600' );
header( 'Location: {to}', true, {status} );
exit;
"""

CONTROLLER = r"""<?php
/**
 * Front controller for the static site on Kinsta.
 * GENERATED by tools/kinsta/build_front_controller.py from _redirects ({count} rules).
 * Edit _redirects and re-run the script; do not edit this file by hand.
 *
 * Kinsta sends any URL that is not a real file or folder to this file:
 *  - "/"                   -> the static homepage
 *  - an old URL in the map -> a permanent redirect to its new page (query strings are kept), or 410 Gone
 *  - "/blog/..."           -> WordPress (installed in /blog)
 *  - anything else         -> the static 404 page
 */
$redirects = array(
{rules}
);

$uri  = isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '/';
$path = rawurldecode( (string) parse_url( $uri, PHP_URL_PATH ) );
$path = preg_replace( '#/{2,}#', '/', $path );

if ( '/' === $path || '/index.php' === $path ) {
	header( 'Content-Type: text/html; charset=UTF-8' );
	readfile( __DIR__ . '/index.html' );
	exit;
}

// Old URLs. Matching ignores a trailing slash and letter case.
$key = strtolower( rtrim( $path, '/' ) );
if ( isset( $redirects[ $key ] ) ) {
	list( $to, $status ) = $redirects[ $key ];
	if ( 410 === $status ) {
		http_response_code( 410 );
		header( 'Content-Type: text/html; charset=UTF-8' );
		readfile( __DIR__ . '/404.html' );
		exit;
	}
	$query = isset( $_SERVER['QUERY_STRING'] ) ? str_replace( array( "\r", "\n" ), '', $_SERVER['QUERY_STRING'] ) : '';
	if ( '' !== $query ) {
		$to .= ( false === strpos( $to, '?' ) ? '?' : '&' ) . $query;
	}
	header( 'Cache-Control: public, max-age=3600' );
	header( 'Location: ' . $to, true, $status );
	exit;
}

if ( '/blog' === $path || 0 === strpos( $path, '/blog/' ) ) {
	$_SERVER['SCRIPT_NAME']     = '/blog/index.php';
	$_SERVER['PHP_SELF']        = '/blog/index.php';
	$_SERVER['SCRIPT_FILENAME'] = __DIR__ . '/blog/index.php';
	chdir( __DIR__ . '/blog' );
	require __DIR__ . '/blog/index.php';
	exit;
}

http_response_code( 404 );
header( 'Content-Type: text/html; charset=UTF-8' );
readfile( __DIR__ . '/404.html' );
"""


def norm(p):
    return p.lower().rstrip('/')


def page_exists(path):
    rel = path.strip('/')
    return (os.path.exists(os.path.join(ROOT, rel, 'index.html'))
            or os.path.isfile(os.path.join(ROOT, rel)))


def main():
    rules, problems = [], []
    for n, line in enumerate(open(os.path.join(ROOT, '_redirects'), encoding='utf-8'), 1):
        if not line.startswith('/'):
            continue
        parts = line.split()
        gone = len(parts) == 3 and parts[1] == '-' and parts[2] == '410'
        if len(parts) != 3 or (parts[2] not in ('301', '302') and not gone):
            problems.append('line %d: expected "<old> <new> <301|302>" or "<old> - 410", got %r' % (n, line.strip()))
            continue
        rules.append((n, parts[0], parts[1], int(parts[2])))

    seen = {}
    for n, old, new, status in rules:
        k = norm(old)
        if k in seen:
            problems.append('line %d: duplicate of line %d (%s)' % (n, seen[k], old))
        seen[k] = n
        if re.search(r'[*:?#]', old):
            problems.append('line %d: wildcards/params are not supported (%s)' % (n, old))
    for n, old, new, status in rules:
        if status == 410:
            continue
        if norm(new) == norm(old):
            problems.append('line %d: redirects to itself (%s)' % (n, old))
        elif norm(new) in seen:
            problems.append('line %d: chain, %s -> %s which is itself redirected' % (n, old, new))
        if not new.startswith('http') and not new.startswith('/blog/') and not page_exists(new):   # blog posts live in WordPress, the test script checks them on the server
            problems.append('line %d: destination %s does not exist in the site' % (n, new))

    if problems:
        print('PROBLEMS:')
        for p in problems:
            print('  -', p)
        sys.exit(1)

    body = '\n'.join("\t'%s' => array( '%s', %d )," % (norm(old).replace("'", "\\'"), new.replace("'", "\\'"), status)
                     for _, old, new, status in sorted(rules, key=lambda r: norm(r[1])))
    open(OUT, 'w', encoding='utf-8').write(CONTROLLER.replace('{count}', str(len(rules))).replace('{rules}', body))

    stubs = []
    for n, old, new, status in rules:
        folder = os.path.join(ROOT, old.strip('/'))
        if status != 410 and os.path.isdir(folder) and os.path.exists(os.path.join(folder, 'index.html')):
            open(os.path.join(folder, 'index.php'), 'w', encoding='utf-8').write(
                HEADER_STUB.replace('{status}', str(status)).replace('{to}', new))
            stubs.append(old)
    print('%d rules -> %s' % (len(rules), os.path.relpath(OUT, ROOT)))
    print('stub folders given a real redirect:', stubs or 'none')


if __name__ == '__main__':
    main()
