<?php
/**
 * Front controller for the static site on Kinsta.
 * GENERATED by tools/kinsta/build_front_controller.py from _redirects (83 rules).
 * Edit _redirects and re-run the script; do not edit this file by hand.
 *
 * Kinsta sends any URL that is not a real file or folder to this file:
 *  - "/"                   -> the static homepage
 *  - an old URL in the map -> a permanent redirect to its new page (query strings are kept)
 *  - "/blog/..."           -> WordPress (installed in /blog)
 *  - anything else         -> the static 404 page
 */
$redirects = array(
	'/about-us-online-marketing-agency' => array( '/about/', 301 ),
	'/ad-creatives' => array( '/performance-creatives/', 301 ),
	'/amazon-ad-management-services' => array( '/amazon-ads/', 301 ),
	'/answer-engine-optimization' => array( '/aeo-ai-search/', 301 ),
	'/bing-advertising-toronto' => array( '/microsoft-ads/', 301 ),
	'/case-studies/comwave' => array( '/case-studies/', 301 ),
	'/case-studies/the-office-shop' => array( '/case-studies/office-shop/', 301 ),
	'/case-study/ecycle-crm' => array( '/case-studies/ecycle/', 301 ),
	'/case-study/tonic-eye-care' => array( '/case-studies/tonic-eye-care/', 301 ),
	'/contact-us' => array( '/contact/', 301 ),
	'/content-marketing-toronto' => array( '/content-marketing/', 301 ),
	'/conversion-rate-optimization' => array( '/cro/', 301 ),
	'/crm-implementation-toronto' => array( '/zoho-crm/', 301 ),
	'/cro-agency-in-toronto' => array( '/cro/', 301 ),
	'/cro-packages' => array( '/cro/', 301 ),
	'/custom-photography-toronto' => array( '/performance-creatives/', 301 ),
	'/digital-growth-plan' => array( '/contact/', 301 ),
	'/digital-marketing-toronto-strategy-development' => array( '/services/', 301 ),
	'/ecommerce-marketing' => array( '/ecommerce-marketing-toronto/', 301 ),
	'/ecommerce-website-development-toronto' => array( '/ecommerce-businesses-website-development-toronto/', 301 ),
	'/email-marketing-toronto' => array( '/marketing-automation/', 301 ),
	'/facebook-advertising-toronto' => array( '/meta-ads/', 301 ),
	'/generative-engine-optimization' => array( '/aeo-ai-search/', 301 ),
	'/google-ads-management-toronto' => array( '/google-ads/', 301 ),
	'/google-business-profile-optimization-toronto' => array( '/local-seo/', 301 ),
	'/google-display-network-advertising-toronto' => array( '/google-ads/', 301 ),
	'/growth-marketing-plan' => array( '/contact/', 301 ),
	'/healthcare-division' => array( '/healthcare/', 301 ),
	'/healthcare-division/strategy-call' => array( '/contact/', 301 ),
	'/healthcare-division/strategy-call/thank-you.html' => array( '/contact/', 301 ),
	'/healthcare-marketing' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/dental-practices' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/med-spas' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/medical-clinics' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/plastic-surgery' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/preventative-health' => array( '/healthcare/', 301 ),
	'/healthcare-marketing/specialty-allied-health' => array( '/healthcare/', 301 ),
	'/healthcare-v2' => array( '/healthcare/', 301 ),
	'/healthcare-v2/work' => array( '/results/', 301 ),
	'/healthcare-v2/work/la-vie' => array( '/case-studies/la-vie/', 301 ),
	'/healthcare-v2/work/tonic-eye-care' => array( '/case-studies/tonic-eye-care/', 301 ),
	'/industries/healthcare' => array( '/healthcare/', 301 ),
	'/influencer-marketing-toronto' => array( '/influencer-marketing/', 301 ),
	'/instagram-marketing-toronto' => array( '/meta-ads/', 301 ),
	'/landing-page-design-toronto' => array( '/landing-pages/', 301 ),
	'/linkedin-advertising-toronto' => array( '/meta-ads/', 301 ),
	'/llm-info' => array( '/aeo-ai-search/', 301 ),
	'/llm-seo-services' => array( '/aeo-ai-search/', 301 ),
	'/locations/la/seo-agency-in-los-angeles' => array( '/locations/los-angeles/seo-agency-in-los-angeles/', 301 ),
	'/locations/nyc/seo-agency-in-new-york-city' => array( '/locations/new-york/seo-agency-in-new-york/', 301 ),
	'/marketing-automation-toronto' => array( '/marketing-automation/', 301 ),
	'/medical' => array( '/healthcare/', 301 ),
	'/off-page-seo' => array( '/seo/', 301 ),
	'/on-page-seo' => array( '/seo/', 301 ),
	'/origin-story' => array( '/about/', 301 ),
	'/our-process' => array( '/about/', 301 ),
	'/portfolio' => array( '/case-studies/', 301 ),
	'/portfolio/asi-group' => array( '/case-studies/', 301 ),
	'/portfolio/comwave' => array( '/case-studies/', 301 ),
	'/portfolio/ecycle-solutions' => array( '/case-studies/ecycle/', 301 ),
	'/portfolio/gorilla-bins' => array( '/case-studies/', 301 ),
	'/portfolio/harmony-resort' => array( '/case-studies/harmony-resorts/', 301 ),
	'/portfolio/ontario-business-central' => array( '/case-studies/ontario-business-central/', 301 ),
	'/portfolio/orr-insurance-investment' => array( '/case-studies/', 301 ),
	'/portfolio/the-office-shop' => array( '/case-studies/office-shop/', 301 ),
	'/portfolio/zayouna-law-firm' => array( '/case-studies/zayouna-law-firm/', 301 ),
	'/programmatic-advertising-toronto' => array( '/google-ads/', 301 ),
	'/remarketing-marketing-toronto' => array( '/google-ads/', 301 ),
	'/reviews' => array( '/case-studies/', 301 ),
	'/sales-enablement-toronto' => array( '/sales-enablement/', 301 ),
	'/sales-letter' => array( '/contact/', 301 ),
	'/self-storage-division' => array( '/self-storage-marketing-toronto/', 301 ),
	'/services/google-ads' => array( '/google-ads/', 301 ),
	'/social-media-marketing-toronto' => array( '/meta-ads/', 301 ),
	'/team' => array( '/about/', 301 ),
	'/tik-tok-advertising-agency-toronto' => array( '/meta-ads/', 301 ),
	'/ugc-creator' => array( '/influencer-marketing/', 301 ),
	'/user-generated-content-agency' => array( '/influencer-marketing/', 301 ),
	'/video-testimonial-toronto' => array( '/performance-creatives/', 301 ),
	'/videographer-toronto' => array( '/performance-creatives/', 301 ),
	'/web-design-toronto' => array( '/web-development/', 301 ),
	'/web-development-toronto' => array( '/web-development/', 301 ),
	'/youtube-advertising-toronto' => array( '/google-ads/', 301 ),
);

$uri  = isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '/';
$path = rawurldecode( (string) parse_url( $uri, PHP_URL_PATH ) );
$path = preg_replace( '#/{2,}#', '/', $path );

if ( '/' === $path || '/index.php' === $path ) {
	header( 'Content-Type: text/html; charset=UTF-8' );
	readfile( __DIR__ . '/index.html' );
	exit;
}

// Old URLs. Matching ignores a trailing slash and letter case.
$key = strtolower( rtrim( $path, '/' ) );
if ( isset( $redirects[ $key ] ) ) {
	list( $to, $status ) = $redirects[ $key ];
	$query = isset( $_SERVER['QUERY_STRING'] ) ? str_replace( array( "\r", "\n" ), '', $_SERVER['QUERY_STRING'] ) : '';
	if ( '' !== $query ) {
		$to .= ( false === strpos( $to, '?' ) ? '?' : '&' ) . $query;
	}
	header( 'Cache-Control: public, max-age=3600' );
	header( 'Location: ' . $to, true, $status );
	exit;
}

if ( '/blog' === $path || 0 === strpos( $path, '/blog/' ) ) {
	$_SERVER['SCRIPT_NAME']     = '/blog/index.php';
	$_SERVER['PHP_SELF']        = '/blog/index.php';
	$_SERVER['SCRIPT_FILENAME'] = __DIR__ . '/blog/index.php';
	chdir( __DIR__ . '/blog' );
	require __DIR__ . '/blog/index.php';
	exit;
}

http_response_code( 404 );
header( 'Content-Type: text/html; charset=UTF-8' );
readfile( __DIR__ . '/404.html' );
