<?php
// GENERATED by tools/kinsta/build_front_controller.py from _redirects. Do not edit by hand.
// A real 301 for this old URL. The index.html beside it stays as a fallback for hosts that cannot redirect.
header( 'Cache-Control: public, max-age=3600' );
header( 'Location: /healthcare/', true, 301 );
exit;
